version: "3"

services:
  dockertest_api:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: dockertest_api
    ports:
      - 80:80
  dockertest_front:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile.production
    image: dockertest_front
    ports:
      - 80:80