FROM node:14-alpine as build

WORKDIR usr/src/app
COPY package.json ./

RUN yarn install --silent

COPY . .
RUN yarn run build:prod

FROM nginx
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
